# Generated by Django 3.0.2 on 2020-01-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
